### ISSUE TITLE
Version 2.0 doesn't work correctly

### ISSUE THREAD

**Issue by AlanBTG** [weespin/KhinsiderDownloader#1]
Hi, I tried 2.0 and it only find 5 random song in an album and then proceeds to download 1 random song from those before getting stuck.

Version 1.1 worked perfectly for me, so thank you for saving me the effort of having to code this myself. I've tried several tools and this is the only one that worked.

**Comment by weespin** [comment]
Can you provide the album link for testing?
I will fix it asap
