### ISSUE TITLE
Download album with photos

### ISSUE THREAD

**Issue by lunaticrave** [weespin/KhinsiderDownloader#11]
When I download the soundtrack, I would like to be able to download the attached scans too, preferably in a separate subdirectory like "scans".

**Comment by BrainwashAlpha** [comment]
this would be a nice feature I would like to see implemented as well. It is tedious to manually download the scans

**Comment by PatrikPepega** [comment]
Same. I would love to see this feature.

**Comment by weespin** [comment]
Added in https://github.com/weespin/KhinsiderDownloader/commit/79b24a38d0dc8bbec5e77237154c225ac4c33299
Please download a new build: https://github.com/weespin/KhinsiderDownloader/releases
