### ISSUE TITLE
Pressing ENTER in search bar creates a new line instead of searching

### ISSUE THREAD

**Issue by PatrikPepega** [weespin/KhinsiderDownloader#12]
Hello, 
I've noticed that when i want to search an album, pressing enter does not actually searches, but it creates a new line in the search box.
Can you please fix that?
Btw: Very nice app. Thank you!

**Comment by weespin** [comment]
Hey @PatrikPepega 👋 
This issue has been fixed! 
Thanks for the suggestion ❤️ 
-------------------
Fixed in https://github.com/weespin/KhinsiderDownloader/issues/12
Released in https://github.com/weespin/KhinsiderDownloader/releases/tag/2.7.4.2
