### ISSUE TITLE
Incorrect folder name and can't download more then one album

### ISSUE THREAD

**Issue by lunaticrave** [weespin/KhinsiderDownloader#15]
Latest version has that problems, it works same with unchecked "download art"
![explorer_tLMrrQTHw9](https://github.com/weespin/KhinsiderDownloader/assets/138993221/17975f7f-da84-406e-ba78-a780ae3dd3a8)

**Comment by lunaticrave** [comment]
I also noticed that some songs didn't download in the downloaded albums

**Comment by lunaticrave** [comment]
Only now I realized that the problem is specifically with these two URLs

**Comment by lunaticrave** [comment]
Downloader can't parse this on old version at all

**Comment by weespin** [comment]
Hey!
This issue should be fixed in [link to the release page](https://github.com/weespin/KhinsiderDownloader/releases/tag/2.7.4.5). 
Please download the new version and let me know if everything works.

**Comment by lunaticrave** [comment]
Now works without any problems, thanks!
