### ISSUE TITLE
Playlists always downloads mp3, even if higher quality is available and selected

### ISSUE THREAD

**Issue by Mimi1001** [weespin/KhinsiderDownloader#16]
Downloading playlists works fine, but the audio quality option seems to be ignored. 
I've attached a video. My example playlist just consists of the first 4 tracks of the "OCTOPATH TRAVELER 16bit Arrangements" album which downloads just fine in FLAC standalone.

https://github.com/weespin/KhinsiderDownloader/assets/53119154/2e76c518-86f9-4214-88ad-bf0fafdbfe43

.

**Comment by weespin** [comment]
Hi 👋 
The current version of the program doesn't support playlists yet

**Comment by Mimi1001** [comment]
Oh, ok ^^ 
But maybe nice for you to know that the program seems to download Playlists just fine in mp3 quality already (I've also tested Playlists comprised of tracks from multiple albums)

**Comment by weespin** [comment]
Hey! That should be fixed in 
https://github.com/weespin/KhinsiderDownloader/releases/tag/2.7.5.0
