### ISSUE TITLE
Add ability to skip already downloaded files

### ISSUE THREAD

**Issue by Nyxenova** [weespin/KhinsiderDownloader#19]
Currently, I've run into no particular issues, other than at times random downloads stop and, it's kind of annoying when mass downloading, it doesn't pick up from where you left off so it basically restarts from the list, so would it be possible for a feature basically asking whether you'd like to replace the existing files or not to be implemented?

**Comment by weespin** [comment]
Added in https://github.com/weespin/KhinsiderDownloader/commit/7bdb84f2f9d4eeda3309322344faceab59ff2bbd
