### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by cwilliams5** [weespin/KhinsiderDownloader#4]
Hey dude, sick software, thanks for making and sharing. 

If I try and download a bunch of albums at once, with Best quality selected, I will eventually always hit an error. Always formatted like this:

Failed to download https://vgmsite.com/soundtracks/the-legend-of-zelda-25th-anniversary-special-orchestra-cd/ugqmrefxrs/08.%20Ballad%20of%20the%20Goddess%20from%20Skyward%20Sword.flac to H:\khinsider\KhinsiderDownloader\Downloads\Legend of Zelda, The - 25th Anniversary Special Orchestra CD\08. Ballad of the Goddess from Skyward Sword.flac (Index was outside the bounds of the array.)

This happens during the 12th or 15th album to be downloaded. Not sure if its song count or album count that hits this limit, but it always hits somewhere in the 12th-15th album. 

If I download 10 albums at a time, and restart the program, it never happens. But, I want to do much more then that at once xD

**Comment by weespin** [comment]
Will check/fix it tomorrow

**Comment by weespin** [comment]
Can you provide me a full list of albums?

**Comment by cwilliams5** [comment]
> I've downloaded 30 albums without any errors 👀

I swear I'm not crazy. OK here is the first 200 links im trying (although you cant paste that many in to KHinsiderDownloader at once. but you can get that many links by repeated searches):

https://pastebin.com/yWak5Uv2

It broke after 12 albums with index out of bounds.
Restart, remove the first 12, it broke again after 15.
Repeated again, broke around 14.
Same again 4th time.

After that I've kept it to 10 at a time with restarts.

I have no idea what I might be doing differently. Just downloaded, dropped on a usb drive, and started using. Windows 10. If I can provide any further details, or any other type of assistance, to help you debug please let me know.

**Comment by weespin** [comment]
A new version is available

**Comment by cwilliams5** [comment]
Working like a charm, latest version fixes the issue!

Hey you don't have a donate link anywhere, I added you on steam so I can give you a tip.
