### ISSUE TITLE
Getting failed to parse on the latest version.

### ISSUE THREAD

**Issue by Revenger** [weespin/KhinsiderDownloader#5]
Latest version isn't working.

![Screenshot 2022-04-09 183708](https://user-images.githubusercontent.com/597280/162568438-57bc5682-20e8-4c15-a146-9758bb9b0a6d.jpg)

**Comment by weespin** [comment]
Fixed in https://github.com/weespin/KhinsiderDownloader/commit/abbab0a56aac7fe0435375f16e79a5b3fb2b5b1d
