### ISSUE TITLE
New To Coding

### ISSUE THREAD

**Issue by SpaceMacce** [weespin/KhinsiderDownloader#6]
Hi, 
I am new to coding and i am having trouble getting this program to work, because i do not know how to open it.

Would you mind have a step-by-step tutorial on how to get it set up and working.

Please and Thankyou.

**Comment by weespin** [comment]
Well, sorry for such big delay.
If you want to build it by yourself, download Visual Studio 2022, copy this repo and open .sln file. Press right click on "Solution ' KhinsiderDownload'" and click on "Restore NuGet Packages". After that just press "Start" to launch your compiled program.
If you just want to run it without building it by yourself  just head over to "https://github.com/weespin/KhinsiderDownloader/releases", open "Assets" tab and download Release.zip file. 
Open/Unpack that zip file and run KhinsiderDownloader.exe
