### ISSUE TITLE
Failed to open url

### ISSUE THREAD

**Issue by scillidan** [weespin/KhinsiderDownloader#8]
![image](https://user-images.githubusercontent.com/19889610/185783865-a85bd6e1-a07e-494c-bf5e-9c012367b383.png)
It say "Unable to connect to the remote server".

**Comment by weespin** [comment]
Everything is working on my PC 
![IMG_20220821_121509_070](https://user-images.githubusercontent.com/17180451/185784224-7c4f994b-59bb-4fa9-877d-53c1ecd6f819.jpg)

**Comment by scillidan** [comment]
Thanks for reply.I guess maybe because I need to use the proxy. 
It is strange that I can open https://downloads.khinsider.com in browser.
But I can't `ping` it 🤨
![image](https://user-images.githubusercontent.com/19889610/185786295-f60e16e7-1ab9-4eb1-bd25-41afc9e83b28.png)

**Comment by scillidan** [comment]
Forget to close the issue. It's right that be a network problem, I agree.
I remember when I used `wget` or `curl`, I needed `wget --no-check-certificate` or `curl -k`. So that they can work properly.
